#######################################################################
## Informações do desenvolvedor:                                     ##
## Dev: Leandro Shiniti Tacara                                       ##
## Email: leandro.tacara@hotmail.com                                 ##
## Github: https://github.com/Lehhh                                  ##
## Linkedin: https://www.linkedin.com/in/leandro-shiniti-tacara/     ##
## Data: 12/06/2020 19:18                                            ##
## projeto: Curso                                                    ##
#######################################################################
spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
  datasource:
    driverClassName: org.postgresql.Driver
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/mvc_dev
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    open-in-view: true
env: dev-test
---
spring:
  profiles: stage
  datasource:
    driverClassName: org.postgresql.Driver
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/mvc_stage
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    open-in-view: true
env: stage-test
---
spring:
  profiles: prod
  datasource:
    driverClassName: org.postgresql.Driver
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/mvc_prod
  jpa:
    dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true
env: prod-test
---